name: alien_signals
description: Alien Signals is a reactive state management library that brings the power of signals to Dart and Flutter applications.

version: 2.1.2
repository: https://github.com/medz/alien-signals-dart

topics:
  - signals
  - reactive
  - state-management
  - alien-signals

funding:
  - https://github.com/sponsors/medz
  - https://opencollective.com/openodroe

screenshots:
  - description: Alien Signals
    path: assets/logo.png

environment:
  sdk: ^3.6.0

dev_dependencies:
  benchmark_harness: ^2.3.1
  lints: 6.1.0
  test: ^1.25.8
