name: alien_signals
description: The lightest signal library - Dart implementation of alien-signals
version: 0.0.1
repository: https://github.com/medz/alien_signals

environment:
  sdk: ^3.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
