name: flutter_alien_signals
description: >-
  Flutter Alien Signals is a Flutter binding based on Alien Signals.
version: 0.2.1
repository: https://github.com/medz/alien-signals-dart/tree/main/pub/flutter_alien_signals
homepage: https://github.com/medz/alien-signals-dart

topics:
  - signal
  - signals
  - reactive
  - alien-signals
  - state

funding:
  - https://github.com/sponsors/medz
  - https://opencollective.com/openodroe

resolution: workspace
environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  alien_signals: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
