name: alien_signals
description: The lightest signal library - Dart implementation of alien-signals.
version: 0.1.0
repository: https://github.com/medz/alien-signals-dart/tree/main/pub/alien_signals
homepage: https://github.com/medz/alien-signals-dart

topics:
  - signal
  - signals
  - reactive
  - alien-signals
  - state

funding:
  - https://github.com/sponsors/medz
  - https://opencollective.com/openodroe

resolution: workspace
environment:
  sdk: ^3.5.0

dev_dependencies:
  lints: ^5.1.0
  test: ^1.25.8
